# docker-compose.yml
version: "3.3"
services:
  frontend:
    build: ./public
    ports:
      - "5002:5002"
    environment:
      - HTTPS=false
      - BACKEND_URL=http://localhost:6002
      - BANK_PLUGIN_URL=http://localhost:7002
    restart: always


  backend:
    build: ./server
    ports:
      - "6002:6002"
    environment:
      - STORAGE_DIR=/data/storage
      - ADMIN_PASSWORD=123456
      - JWT_SECRET=123456
    volumes:
      - projects:/data/storage
    restart: always

  bank:
    build: ./bank
    ports:
      - "7002:7002"
    environment:
      - HTTPS=false
    restart: always

volumes:
    projects:
