# docker-compose.yml
version: "3.3"
services:
  frontend:
    build: ./public
    ports:
      - "7002:7002"
    environment:
      - HTTPS=false
    restart: unless-stopped

  bank:
    build: ./bank
    ports:
      - "8002:8002"
    environment:
      - HTTPS=false
      - STORAGE_DIR=/data/storage
    volumes:
      - projects:/data/storage
    restart: unless-stopped

volumes:
  projects:
