# docker-compose.yml
version: "3.3"
services:
  attune:
    build: ./public
    ports:
      - "7002:7002"
    environment:
      - HTTPS=false
    restart: unless-stopped

  attune-bank:
    build: ./bank
    ports:
      - "8002:8002"
    environment:
      - HTTPS=true
      - STORAGE_DIR=/data/storage
    volumes:
      - attune-projects:/data/storage
    restart: unless-stopped

volumes:
  attune-projects:
